# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import os

from spack_repo.builtin.build_systems.generic import Package

from spack.package import *


class Max(Package):
    """MAX CLI, Python components, and Mojo kernels from Modular's public Bazel repository."""

    homepage = "https://www.modular.com/max"
    git = "https://github.com/modular/modular.git"

    license("Apache-2.0 WITH LLVM-exception")

    # Public source tags do not currently expose a 26.8 release. This commit is
    # the inspected main revision whose Bazel metadata reports MAX 26.6.0.dev2026082305.
    version(
        "26.6.0-dev20260823",
        commit="10d978e3c783ef940d1d30d0a10852b69fe285c8",
        preferred=True,
    )

    variant("release_type", default="production", values=("dev", "production"), multi=False,
            description="Modular release type passed to Bazel")

    depends_on("c", type="build")
    depends_on("cxx", type="build")
    depends_on("bash", type="build")
    depends_on("curl", type="build")
    depends_on("git", type="build")
    depends_on("java@21:", type="build")
    depends_on("python@3.13", type=("build", "run"))
    depends_on("zip", type="build")
    depends_on("unzip", type="build")
    depends_on("zlib-api", type="link")
    depends_on("zstd", type="link")
    # Co-install the source-built Mojo CLI in the uenv view. Bazel still builds
    # MAX's Mojo targets from this source checkout with --config=build-mojo.
    depends_on("mojo@1.1.0-dev20260823", type="run")

    python_component_targets = (
        "//max/python/max/pipelines:pipelines",
        "//max/python/max/serve:serve",
        "//max/python/max/serve/pipelines:pipelines",
    )

    mojo_kernel_targets = (
        "//max:algorithm",
        "//max:builtin_kernels",
        "//max:builtin_primitives",
        "//max:comm",
        "//max:extensibility",
        "//max:internal_utils",
        "//max:kv_cache",
        "//max:layout",
        "//max:linalg",
        "//max:max_mojo",
        "//max:nn",
        "//max:pipeline",
        "//max:profiling_range",
        "//max:quantization",
        "//max:shmem",
        "//max:state_space",
        "//max:structured_kernels",
        "//max:weights_registry",
        "//max:_cublas",
        "//max:_cudnn",
        "//max:_cufft",
        "//max:_miopen",
        "//max:_rocblas",
    )

    def setup_build_environment(self, env):
        cache_root = join_path(self.stage.path, "bazel-cache")
        env.set("BAZELISK_HOME", join_path(cache_root, "bazelisk"))
        env.set("XDG_CACHE_HOME", join_path(cache_root, "xdg"))
        env.set("PYTHON_BIN_PATH", self.spec["python"].command.path)
        env.set("MODULAR_CRASH_REPORTING_ENABLED", "0")

    @property
    def bazel(self):
        return Executable(join_path(self.stage.source_path, "bazelw"))

    def bazel_args(self):
        args = [
            "--output_user_root=" + join_path(self.stage.path, "bazel-output-user-root"),
            "build",
            "--color=no",
            "--verbose_failures",
            "--jobs={0}".format(make_jobs),
            "--config=build-mojo",
            "--compilation_mode=opt",
            "--//:release_type={0}".format(self.spec.variants["release_type"].value),
            "--//:mojo_base_version=1.1.0",
            "--//:mojo_version_label=.dev2026082305",
            "--//:max_base_version=26.6.0",
            "--//:max_version_label=.dev2026082305",
            "//max:max",
        ]
        args.extend(self.python_component_targets)
        args.extend(self.mojo_kernel_targets)
        return args

    def generate_wrapper_bazelrc(self):
        build_dir = join_path(self.stage.source_path, "build")
        mkdirp(build_dir)

        detect_resources = Executable(
            join_path(self.stage.source_path, "bazel", "internal", "detect_local_resources.sh")
        )
        local_resources = detect_resources(output=str)
        with open(join_path(build_dir, "local-resources.bazelrc"), "w") as f:
            f.write(local_resources)

        with open(join_path(build_dir, "wrapper.bazelrc"), "w") as f:
            f.write("# Generated by the Spack max package.\n")
            f.write("build --build_metadata=USER=spack\n")
            f.write("import %workspace%/build/local-resources.bazelrc\n")

    def patch_gh200_gpu_mapping(self):
        module_file = join_path(self.stage.source_path, "bazel", "common.MODULE.bazel")
        with open(module_file) as f:
            contents = f.read()

        if '"GH200": "h100"' in contents:
            return

        contents = contents.replace(
            '        " H200": "h200",\n',
            '        " H200": "h200",\n        "GH200": "h100",\n',
        )

        with open(module_file, "w") as f:
            f.write(contents)

    def find_launcher(self):
        bazel_bin = join_path(self.stage.source_path, "bazel-bin")
        candidates = [
            join_path(bazel_bin, "max", "python", "max", "_entrypoints", "pipelines"),
            join_path(bazel_bin, "max", "max"),
        ]
        for candidate in candidates:
            if os.path.exists(candidate):
                return candidate

        for root, dirs, files in os.walk(bazel_bin):
            dirs[:] = [d for d in dirs if not d.endswith(".runfiles")]
            for filename in ("pipelines", "max"):
                candidate = join_path(root, filename)
                if filename in files and os.access(candidate, os.X_OK):
                    return candidate

        raise InstallError("expected Bazel MAX launcher not found under {0}".format(bazel_bin))

    def install_runfiles(self, runfiles, manifest, destination):
        if os.path.isdir(runfiles):
            install_tree(runfiles, destination)
            return

        if not os.path.exists(manifest):
            raise InstallError(
                "expected Bazel runfiles directory or manifest not found: {0}".format(runfiles)
            )

        mkdirp(destination)
        with open(manifest) as f:
            for line in f:
                fields = line.rstrip("\n").split(" ", 1)
                if len(fields) != 2:
                    continue

                relative_path, source_path = fields
                target_path = join_path(destination, relative_path)
                mkdirp(os.path.dirname(target_path))

                if os.path.isdir(source_path):
                    install_tree(source_path, target_path)
                elif os.path.exists(source_path):
                    install(source_path, target_path)
                else:
                    raise InstallError(
                        "runfiles manifest entry source not found: {0}".format(source_path)
                    )

    def install_shared_libraries(self, runfiles):
        library_dir = join_path(self.prefix.lib, "max")
        mkdirp(library_dir)
        for root, dirs, files in os.walk(runfiles):
            if "/modular/lib" not in root:
                continue

            for filename in files:
                if not (filename.endswith(".so") or ".so." in filename):
                    continue

                destination = join_path(library_dir, filename)
                if not os.path.exists(destination):
                    install(join_path(root, filename), destination)

    def install(self, spec, prefix):
        self.patch_gh200_gpu_mapping()
        self.generate_wrapper_bazelrc()
        self.bazel(*self.bazel_args())

        launcher = self.find_launcher()
        runfiles = launcher + ".runfiles"
        manifest = launcher + ".runfiles_manifest"

        libexec = join_path(prefix, "libexec", "max")
        mkdirp(prefix.bin)
        mkdirp(libexec)
        install(launcher, join_path(libexec, "pipelines"))
        installed_runfiles = join_path(libexec, "pipelines.runfiles")
        self.install_runfiles(runfiles, manifest, installed_runfiles)
        self.install_shared_libraries(installed_runfiles)

        wrapper = join_path(prefix.bin, "max")
        with open(wrapper, "w") as f:
            f.write("#!/bin/sh\n")
            f.write("set -eu\n")
            f.write('script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\n')
            f.write('prefix=$(CDPATH= cd -- "$script_dir/.." && pwd)\n')
            f.write('libexec="$prefix/libexec/max"\n')
            f.write('export MODULAR_CRASH_REPORTING_ENABLED="${MODULAR_CRASH_REPORTING_ENABLED:-0}"\n')
            f.write('export RUNFILES_DIR="${MAX_RUNFILES_DIR:-$libexec/pipelines.runfiles}"\n')
            f.write('export TEST_SRCDIR="${TEST_SRCDIR:-$RUNFILES_DIR}"\n')
            f.write('export LD_LIBRARY_PATH="$prefix/lib/max:$prefix/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"\n')
            f.write('mojo_import_path="${MODULAR_MOJO_MAX_IMPORT_PATH:-}"\n')
            f.write('add_mojo_import_path() {\n')
            f.write('    [ -d "$1" ] || return\n')
            f.write('    case ",$mojo_import_path," in\n')
            f.write('        *,"$1",*) ;;\n')
            f.write('        *) mojo_import_path="${mojo_import_path:+$mojo_import_path,}$1" ;;\n')
            f.write('    esac\n')
            f.write('}\n')
            f.write('for dir in "$RUNFILES_DIR"/*module_platlib_linux_aarch64*/modular; do\n')
            f.write('    [ -d "$dir" ] || continue\n')
            f.write('    max_root="$dir"\n')
            f.write('    break\n')
            f.write('done\n')
            f.write('if [ -n "${max_root:-}" ]; then\n')
            f.write('    export MODULAR_MAX_PACKAGE_ROOT="${MODULAR_MAX_PACKAGE_ROOT:-$max_root}"\n')
            f.write('    export MODULAR_MOJO_MAX_PACKAGE_ROOT="${MODULAR_MOJO_MAX_PACKAGE_ROOT:-$max_root}"\n')
            f.write('    if [ -z "${MODULAR_MOJO_MAX_DRIVER_PATH:-}" ]; then\n')
            f.write('        if [ -x "$prefix/bin/mojo" ]; then\n')
            f.write('            export MODULAR_MOJO_MAX_DRIVER_PATH="$prefix/bin/mojo"\n')
            f.write('        elif command -v mojo >/dev/null 2>&1; then\n')
            f.write('            export MODULAR_MOJO_MAX_DRIVER_PATH="$(command -v mojo)"\n')
            f.write('        fi\n')
            f.write('    fi\n')
            f.write('    if [ -d "$max_root/lib/mojo" ]; then\n')
            f.write('        add_mojo_import_path "$max_root/lib/mojo"\n')
            f.write('    fi\n')
            f.write('fi\n')
            f.write('add_mojo_import_path "$RUNFILES_DIR/_main/mojo/stdlib/std"\n')
            f.write('add_mojo_import_path "$RUNFILES_DIR/_main/max/mojo/max"\n')
            f.write('for dir in "$RUNFILES_DIR"/_main/max/kernels/src/* "$RUNFILES_DIR"/_main/max/kernels/src/graph_compiler/*; do\n')
            f.write('    [ -d "$dir" ] || continue\n')
            f.write('    name=$(basename "$dir")\n')
            f.write('    [ -f "$dir/$name.mojoc" ] || continue\n')
            f.write('    add_mojo_import_path "$dir"\n')
            f.write('done\n')
            f.write('if [ -n "$mojo_import_path" ]; then\n')
            f.write('    export MODULAR_MOJO_MAX_IMPORT_PATH="$mojo_import_path"\n')
            f.write('fi\n')
            f.write('for dir in "$RUNFILES_DIR"/*nvshmem_prebuilt*; do\n')
            f.write('    [ -d "$dir" ] || continue\n')
            f.write('    export MODULAR_SHMEM_LIB_DIR="${MODULAR_SHMEM_LIB_DIR:-$dir}"\n')
            f.write('    break\n')
            f.write('done\n')
            f.write('exec "$libexec/pipelines" "$@"\n')
        os.chmod(wrapper, 0o755)

    def setup_run_environment(self, env):
        env.prepend_path("PATH", self.prefix.bin)
        env.prepend_path("LD_LIBRARY_PATH", join_path(self.prefix.lib, "max"))
        env.set("MODULAR_CRASH_REPORTING_ENABLED", "0")

    @run_after("install")
    @on_package_attributes(run_tests=True)
    def install_test(self):
        max_cli = Executable(join_path(self.prefix.bin, "max"))
        max_cli("--help")
