# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import os

from spack_repo.builtin.build_systems.generic import Package

from spack.package import *


class Mojo(Package):
    """Mojo compiler/toolchain from Modular's open-source Bazel repository."""

    homepage = "https://www.modular.com/mojo"
    git = "https://github.com/modular/modular.git"

    license("Apache-2.0 WITH LLVM-exception")

    # Public source tags do not currently expose a 26.8 release. This commit is
    # the inspected main revision whose Bazel metadata reports Mojo 1.1.0.dev2026082305.
    version(
        "1.1.0-dev20260823",
        commit="10d978e3c783ef940d1d30d0a10852b69fe285c8",
        preferred=True,
    )
    version("1.0.0", tag="mojo/v1.0.0")

    variant("release_type", default="production", values=("dev", "production"), multi=False,
            description="Modular release type passed to Bazel")

    depends_on("c", type="build")
    depends_on("cxx", type="build")
    depends_on("bash", type="build")
    # Build-time dep so the newer Spack amd-smi (which emits the
    # {"gpu_data": [...]} wrapper that upstream detect_local_resources.sh
    # expects) is on PATH during generate_wrapper_bazelrc. The system
    # /usr/bin/amd-smi is older and emits a bare array, which makes
    # detect_local_resources.sh fail during the MI300 build.
    depends_on("amdsmi", type="build")
    depends_on("curl", type="build")
    depends_on("git", type="build")
    depends_on("java@21:", type="build")
    depends_on("python@3.13", type=("build", "run"), when="@1.1.0-dev20260823")
    depends_on("python@3.10:", type=("build", "run"))
    depends_on("zip", type="build")
    depends_on("unzip", type="build")
    depends_on("zlib-api", type="link")
    depends_on("zstd", type="link")

    def setup_build_environment(self, env):
        cache_root = join_path(self.stage.path, "bazel-cache")
        env.set("BAZELISK_HOME", join_path(cache_root, "bazelisk"))
        env.set("XDG_CACHE_HOME", join_path(cache_root, "xdg"))
        env.set("PYTHON_BIN_PATH", self.spec["python"].command.path)
        env.set("MODULAR_CRASH_REPORTING_ENABLED", "0")

    @property
    def bazel(self):
        return Executable(join_path(self.stage.source_path, "bazelw"))

    def bazel_args(self):
        args = [
            "--output_user_root=" + join_path(self.stage.path, "bazel-output-user-root"),
            "build",
            "--color=no",
            "--verbose_failures",
            "--jobs={0}".format(make_jobs),
            "--config=build-mojo",
            "--compilation_mode=opt",
            "--//:release_type={0}".format(self.spec.variants["release_type"].value),
        ]

        if self.spec.satisfies("@1.1.0-dev20260823"):
            args.extend([
                "--//:mojo_base_version=1.1.0",
                "--//:mojo_version_label=.dev2026082305",
                "--//:max_base_version=26.6.0",
                "--//:max_version_label=.dev2026082305",
            ])

        args.append("//KGEN:mojo")
        return args

    def generate_wrapper_bazelrc(self):
        build_dir = join_path(self.stage.source_path, "build")
        mkdirp(build_dir)

        detect_resources = Executable(
            join_path(self.stage.source_path, "bazel", "internal", "detect_local_resources.sh")
        )
        local_resources = detect_resources(output=str)
        with open(join_path(build_dir, "local-resources.bazelrc"), "w") as f:
            f.write(local_resources)

        with open(join_path(build_dir, "wrapper.bazelrc"), "w") as f:
            f.write("# Generated by the Spack mojo package.\n")
            f.write("build --build_metadata=USER=spack\n")
            f.write("import %workspace%/build/local-resources.bazelrc\n")

    def install_runfiles(self, runfiles, manifest, destination):
        if os.path.isdir(runfiles):
            install_tree(runfiles, destination)
            return

        if not os.path.exists(manifest):
            raise InstallError(
                "expected Bazel runfiles directory or manifest not found: {0}".format(runfiles)
            )

        mkdirp(destination)
        with open(manifest) as f:
            for line in f:
                fields = line.rstrip("\n").split(" ", 1)
                if len(fields) != 2:
                    continue

                relative_path, source_path = fields
                target_path = join_path(destination, relative_path)
                mkdirp(os.path.dirname(target_path))

                if os.path.isdir(source_path):
                    install_tree(source_path, target_path)
                elif os.path.exists(source_path):
                    install(source_path, target_path)
                else:
                    raise InstallError(
                        "runfiles manifest entry source not found: {0}".format(source_path)
                    )

    def install_runtime_libraries(self, runfiles):
        # Bazel names its solib symlink tree after the host architecture
        # (e.g. _solib_aarch64 on GH200, _solib_x86_64 on MI300/x86). Scan all
        # _solib_* directories so the wrapper is portable across arches.
        for entry in os.listdir(runfiles):
            if not entry.startswith("_solib_"):
                continue

            solib_root = join_path(runfiles, entry)
            for directory in ("_UKGEN", "_UAsyncRT", "_USupport"):
                lib_dir = join_path(solib_root, directory)
                if not os.path.isdir(lib_dir):
                    continue

                for filename in os.listdir(lib_dir):
                    if ".so" not in filename:
                        continue

                    destination = join_path(self.prefix.lib, filename)
                    if not os.path.exists(destination):
                        install(join_path(lib_dir, filename), destination)

    def install(self, spec, prefix):
        # No GPU-mapping patch is needed on MI300: upstream common.MODULE.bazel
        # already maps "MI300A" -> "mi300a" -> "amdgpu:gfx942" (rules_mojo
        # matches the amd-smi board.product_name, which contains "MI300A").
        self.generate_wrapper_bazelrc()
        self.bazel(*self.bazel_args())

        binary = join_path(self.stage.source_path, "bazel-bin", "KGEN", "tools", "mojo", "mojo-full")
        runfiles = binary + ".runfiles"
        manifest = binary + ".runfiles_manifest"
        if not os.path.exists(binary):
            raise InstallError("expected Bazel output not found: {0}".format(binary))

        libexec = join_path(prefix, "libexec", "mojo")
        mkdirp(prefix.bin)
        mkdirp(libexec)
        install(binary, join_path(libexec, "mojo"))
        installed_runfiles = join_path(libexec, "mojo-full.runfiles")
        self.install_runfiles(runfiles, manifest, installed_runfiles)
        self.install_runtime_libraries(installed_runfiles)

        wrapper = join_path(prefix.bin, "mojo")
        with open(wrapper, "w") as f:
            f.write("#!/bin/sh\n")
            f.write("set -eu\n")
            f.write('script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\n')
            f.write('prefix=$(CDPATH= cd -- "$script_dir/.." && pwd)\n')
            f.write('libexec="$prefix/libexec/mojo"\n')
            f.write('export MODULAR_CRASH_REPORTING_ENABLED="${MODULAR_CRASH_REPORTING_ENABLED:-0}"\n')
            f.write('export RUNFILES_DIR="${MOJO_RUNFILES_DIR:-$libexec/mojo-full.runfiles}"\n')
            f.write('export TEST_SRCDIR="${TEST_SRCDIR:-$RUNFILES_DIR}"\n')
            f.write('export MODULAR_MOJO_MAX_IMPORT_PATH="${MODULAR_MOJO_MAX_IMPORT_PATH:-$RUNFILES_DIR/_main/mojo/stdlib/std}"\n')
            # Bazel names its solib symlink tree after the host architecture
            # (_solib_aarch64 on GH200, _solib_x86_64 on MI300/x86). Collect
            # every _solib_* directory so the wrapper works on either arch.
            f.write('solib_path=""\n')
            f.write('for dir in "$RUNFILES_DIR"/_main/_solib_*; do\n')
            f.write('    [ -d "$dir" ] || continue\n')
            f.write('    solib_path="${solib_path:+$solib_path:}$dir"\n')
            f.write('done\n')
            f.write('if [ -n "$solib_path" ]; then\n')
            f.write('    export LD_LIBRARY_PATH="$solib_path${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"\n')
            f.write('fi\n')
            f.write('exec "$libexec/mojo" "$@"\n')
        os.chmod(wrapper, 0o755)

    def setup_run_environment(self, env):
        env.prepend_path("PATH", self.prefix.bin)
        env.prepend_path("LD_LIBRARY_PATH", self.prefix.lib)
        env.set("MODULAR_CRASH_REPORTING_ENABLED", "0")

    @run_after("install")
    @on_package_attributes(run_tests=True)
    def install_test(self):
        mojo = Executable(join_path(self.prefix.bin, "mojo"))
        mojo("--version")
