ml-base-env:
  compiler:
      - toolchain: gcc
        spec: gcc
      - toolchain: llvm
        spec: llvm@18
  mpi:
      spec: cray-mpich@8.1.29
      gpu: cuda
  unify: true
  specs:
  - aws-ofi-nccl@master%gcc
  - xpmem%gcc
  - cmake%gcc
  - cuda@12.3%gcc
  - fftw%gcc
  - fmt%gcc
  - hdf5%gcc
  - nccl%gcc
  - ninja%gcc
  - gperftools%gcc
  - openblas%gcc threads=openmp
  #- armpl-gcc%gcc threads=openmp
  - cudnn%gcc
  - cutensor%gcc
  - swig%gcc
  - libaio%gcc
  - python@3.11%gcc
  - py-pip%gcc
  - py-cython%gcc
  - py-setuptools%gcc
  - py-setuptools-scm%gcc +toml
  - py-setuptools-rust%gcc
  - py-wheel%gcc
  - py-packaging%gcc
  - py-pathspec%gcc
  - py-pybind11%gcc
  - py-pluggy%gcc
  - py-ninja%gcc
  - py-numpy%gcc
  - py-sympy%gcc
  - py-scipy%gcc
  - py-pytest%gcc
  - py-pytest-xdist%gcc
  - py-torch@2.2%gcc +distributed +cuda +cudnn +nccl +mpi
  - py-torchvision%gcc +ffmpeg +nvjpeg +video_codec
  - py-torchaudio%gcc
  - py-torchmetrics%gcc
  #- py-torch-nvidia-apex@master%gcc
  - py-huggingface-hub%gcc
  - py-nvidia-dali%gcc
  - py-zarr%gcc
  #- py-onnx%gcc
  - py-nvtx%gcc
  - py-deepspeed%gcc
  - py-accelerate%gcc
  - py-datasets%gcc
  - py-tokenizers%gcc
  - sentencepiece@0.1.99%gcc ~with-TCMalloc
  - py-sentencepiece@0.1.99%gcc
  - py-transformers%gcc
  - py-einops%gcc
  - py-hatchling%gcc
  - arrow%gcc +parquet +snappy +zlib +zstd +brotli +compute 
  - py-nltk%gcc
  #- py-psutil
  #- py-pydantic
  #- py-click
  #- py-joblib
  #- py-astunparse
  #- py-calver
  #- py-certifi
  #- py-charset-normalizer
  #- py-decorator
  #- py-dm-tree
  #- py-docutils
  #- py-editables
  #- py-filelock
  #- py-flit-core
  #- py-protobuf
  #- py-fsspec
  #- py-gast
  #- py-hatchling
  #- py-hatch-vcs
  #- py-idna
  #- py-jinja2
  #- py-lightning-utilities
  #- py-markupsafe
  #- py-mpmath
  #- py-pyproject-metadata
  #- py-requests
  #- py-six
  #- py-tomli
  #- py-tqdm
  #- py-trove-classifiers
  #- py-typing-extensions
  #- py-urllib3
  #- py-networkx +default
  #- py-pillow +jpeg +zlib
  #- py-pyyaml +libyaml
  #- py-versioneer +toml
  #- py-yarl
  #- py-transformers
  #- py-datasets
  #- py-tensorboardx
  #- py-execnet
  ##- py-arrow
  #- arrow +parquet +snappy +zlib +zstd +brotli +compute 
  #- py-pyarrow +dataset +parquet
  #- py-iniconfig
  #- py-maturin
  #- py-multidict
  #- py-regex
  #- py-safetensors
  #- py-semantic-version
  #- py-tokenizers
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: all
